# Generated by Django 4.1.3 on 2022-11-09 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_user_secret_word_user_type_secret_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='secret_word',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Секретное слово'),
        ),
        migrations.AlterField(
            model_name='user',
            name='type_secret_word',
            field=models.CharField(blank=True, choices=[('Hometown', 'Родной город'), ('PetName', 'Имя домашнего питомца'), ('ChildDream', 'Кем вы хотели стать в детстве'), ('Hobby', 'Ваше хобби')], max_length=255, null=True, verbose_name='Тип секретного слова'),
        ),
    ]
